#!/usr/bin/perl
use strict;

my $count;
my @disks;

# output needs to look like 
# mdadm -v --create /dev/md0 --level=raid10 --raid-devices=$number_of_drives $list_of_drives 

open(FH,"fdisk -l 2>/dev/null | "); 
while ( <FH> ) { 
	chomp $_;
	# Get us a line like 
	# Disk /dev/sdae: 3000.6 GB, 3000592982016 bytes	
	# then we need /dev/sdk portion
	if ($_ =~m/^Disk\s(\/dev\/\w+):.*3000.6.*bytes/) { 
	push (@disks, $1);
  }
} 

$count = scalar (@disks); 
print "mdadm -v --create /dev/md0 --level=raid10 --raid-devices=$count @disks\n" 
