#!/usr/bin/perl 

# Take a list of mac addresses and create dhcp lease info for them 

my $base = "web_server";    # base name for server
my $network="10.100.100";   # network for the server  
my $i=1;                    # starting digit of hostname
my $ip_tail=35;             # starting digit of final ip octet
my $digitcount=3;           # total digits in name 

my @macs = ( 
  "f0:1f:fa:cc:5e:f9",
  "f0:1f:fa:cc:5f:ce",
  "f0:1f:fa:cc:60:be",
  "f0:1f:fa:cc:63:88",
  "f0:1f:fa:cc:5e:4f",
);

foreach (@macs) { 
  my $digi = &leading_zeros ($i, $digitcount); 
  my $hostname = "${base}${digi}";
  my $ip = "${network}.${tail}";
  print "host $hostname { \n";
  print "            hardware ethernet $_\;\n";
  print "            fixed-address $ip\;\n";
  print "            option host-name \"$hostname\"\;\n";
  print "      }\n";
  print "\n";

  # increment hostname and ip 
  $i++;
  $ip_tail++; 
}

# sample output for a single record 
#host newbox-1 {
#            hardware ethernet f0:1f:af:dd:2e:f9;
#            fixed-address 10.100.104.;
#            option host-name "nyc-memster12";
#      }

######### 
sub leading_zeros { 
  my $num = sprintf("%0$_[1]s", $_[0]); 
  return $num; 
} 
