#!/bin/sh 

user=mmedeiros
url=https://github.com/$user/dotfiles/archive/master.tar.gz 
path=/home/$user
tmp=dot.tar.gz

echo "curl -L $url >>$tmp 2>/dev/null && tar -xzf $tmp && mv -f dotfiles-master/.[^.]* $path && rm -rf $path/dotfiles-master && rm $tmp && source $path/.bashrc"
