#!/bin/sh

# user info
gituser=mmedeiros    # user on github
localuser=mmedeiros  # user on the box

# Git info
repo='dotfiles'
branch='master'

# Derived variables
url="https://github.com/$gituser/$repo/archive/$branch.tar.gz"
path=/home/$localuser
tmp=dot.tar.gz
vimdir="/usr/share/vim/vim74/"

cleanup="rm -rf $path/.vim* && \
          rm -rf $path/.bash* "

command="curl -L $url >>$tmp 2>/dev/null && \
          tar -xzf $tmp && \
          mv -f ${repo}-${branch}/.[^.]* $path && \
          rm -rf $path/${repo}-${branch} && \
          rm $tmp && \
          source $path/.bashrc"

vimcolors="sudo cp -n $path/.vim/colors/* $vimdir/colors/"

echo "$cleanup && $command && $vimcolors" | tr -s ' '
